# Generated by Django 4.2.6 on 2023-12-27 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('Tname', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
